# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import qr_pb2 as qr__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class qrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPhotos = channel.stream_unary(
                '/qr.qr/UploadPhotos',
                request_serializer=qr__pb2.PhotoChunk.SerializeToString,
                response_deserializer=qr__pb2.UploadSummary.FromString,
                _registered_method=True)


class qrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadPhotos(self, request_iterator, context):
        """client streaming: клиент шлёт последовательность PhotoChunk, сервер в конце возвращает UploadSummary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_qrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPhotos': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadPhotos,
                    request_deserializer=qr__pb2.PhotoChunk.FromString,
                    response_serializer=qr__pb2.UploadSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qr.qr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qr.qr', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class qr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPhotos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/qr.qr/UploadPhotos',
            qr__pb2.PhotoChunk.SerializeToString,
            qr__pb2.UploadSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
